POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjc4OGVmNTVhZjI3NDFlMmZhZGE4ZThkIiwiaWF0IjoxNzM3MTI1NzE1LCJleHAiOjE3MzcxMjkzMTV9.lhDGRTOktmS8_QvV3GKWYWWrTduicSY9sr8zZRkdK6o

{
  "title": "try userExtractor",
  "author": "try userExtractor",
  "url": "try userExtractor",
  "likes": 7
}









